name       : haskell-network
version    : 2.6.3.1
release    : 2
source     :
    - http://hackage.haskell.org/package/network-2.6.3.1/network-2.6.3.1.tar.gz : 57045f5e2bedc095670182130a6d1134fcc65d097824ac5b03933876067d82e6
license    : BSD-3-Clause
component  : programming
summary    : This package provides a low-level networking interface.
description: |
    This package provides a low-level networking interface.
builddeps  :
    - ghc
setup      : |
    ghc -threaded Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 network-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/network-$version.conf
patterns   :
    - devel :
        - /usr/lib64/ghc-8.0.1/network-2.6.3.1/include
