name       : haskell-network
version    : 2.7.0.0
release    : 10
source     :
    - https://hackage.haskell.org/package/network-2.7.0.0/network-2.7.0.0.tar.gz : c10546f4846f53a0b4b65538bc4fd5db6d4b5d3ac69447e6114be0be0f1a0d9f
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides a low-level networking interface.
description: |
    This package provides a low-level networking interface.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
optimize   : no-symbolic
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
patterns   :
    - devel :
        - /usr/lib64/ghc-*/network-*/include
