name       : haskell-network
version    : 3.1.4.0
release    : 12
source     :
    - https://hackage.haskell.org/package/network-3.1.4.0/network-3.1.4.0.tar.gz : b452a2afac95d9207357eb3820c719c7c7d27871ef4b6ed7bfcd03a036b9158e
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides a low-level networking interface.
description: |
    This package provides a low-level networking interface.
builddeps  :
    - ghc-devel
setup      : |
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
patterns   :
    - devel :
        - /usr/lib64/ghc-*/network-*/include
