name       : haskell-network
version    : 2.6.3.1
release    : 9
source     :
    - https://hackage.haskell.org/package/network-2.6.3.1/network-2.6.3.1.tar.gz : 57045f5e2bedc095670182130a6d1134fcc65d097824ac5b03933876067d82e6
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides a low-level networking interface.
description: |
    This package provides a low-level networking interface.
builddeps  :
    - binutils-gold
    - ghc-devel
    - haskell-cabal-install
setup      : |
    %cabal_configure --ghc-options="-optl-fuse-ld=gold" --ld-options="-fuse-ld=gold"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
patterns   :
    - devel :
        - /usr/lib64/ghc-*/network-*/include
